### ISSUE TITLE
Started new branch "A"

### ISSUE THREAD

**Issue by chanana** [chanana/courseNotes#3]
@morrowcj I started a new branch called `A`.
Your turn!

**Comment by morrowcj** [comment]
@chanana, 

Ok I did all of the steps on my end and then I merged my master branch with my B and pushed it to the github master branch. After you do the rest of the steps, you'll have to do the pull 1st before pushing part.

**Comment by morrowcj** [comment]
Network link: https://github.com/chanana/courseNotes/network

**Comment by chanana** [comment]
@morrowcj 

- [x] pair up with one other student in the class
- [x] decide which git repository to work on: class note repo from one or the other student, say student A
- [x] **student A** goes to her/his own repository, clicks on “Settings” then “Collaborator” (github might ask for your password) then enters the gihub user name for student B, then click “Add collaborator”: to give push access to student B
- [x] **student A**: start a new branch “A”, add something to it, push the branch to github
- [x] **student B**: clone the repo on her/his laptop, start new branch “B”, add changes or new file to it, push the branch to github
- [x] **student A**: pull branch B, add changes to it, push to GitHub
- [x] **student B**: pull branch A, add changes to it, push to GitHub
- [x] **student A and B**: each checkout master branch, merge his/her own branch into master, push to GitHub. The second student doing this will need to pull first.
- [x] **both students**: check the branches and merge on the repo’s network: click on “Insights” then “Network”; there should be at least 1 merge commit and labels for at least 3 branches: master, A and B.
- [x] open a github issue with a link to the url with the “network” view *[done by B]*;
- [x] tag the instructor & TA on this issue, give both student names.

Edited because completed

**Comment by morrowcj** [comment]
I already did those things. Did they not get pushed?



- Clay Morrow


-------- Original message --------

**Comment by chanana** [comment]
I guess I did too but the steps are in order so I'm not sure if the TA/Instructor will check that they all happened in that order.

**Comment by chanana** [comment]
~@morrowcj ~
~Undid some stupid things I did and merged. I think we should both be good now. Please check once and then either go ahead and tag 'em or I can do it. Sorry for complicating this unnecessarily!~

~Ok turns out I shouldn't have merged B again. So I'll un-merge that and let you merge it again. Sorry again!~

Edit: I think we should start a new project...

**Comment by morrowcj** [comment]
@chanana, I just looked at the network and I think you just need to merge your version of A into the master branch, fix any conflicts, pull the upstream changes and fix conflicts again, and then push. Then we should be done.

But if you want to start a new project to make the network a bit cleaner, that's ok too.

**Comment by chanana** [comment]
@morrowcj, I merged my branch with the master branch and pushed.

**Comment by chanana** [comment]
- TA - @coraallencoleman and  
 - Instructor: @cecileane
 - Students:
    - @chanana `Shaurya Chanana` and 
    - @morrowcj `Clay Morrow`
- [Network Link](https://github.com/chanana/courseNotes/network)

**Comment by cecileane** [comment]
beautiful network, and beautiful checklist! :100:
