### ISSUE TITLE
Completed_binomial.py_Shaurya-Chanana

### ISSUE THREAD

**Issue by chanana** [chanana/courseNotes#4]
### [This script](https://github.com/chanana/courseNotes/blob/master/binomial.py) was written for `python3` and tested on `macOS 10.14`

* The first line of the script is `#! /usr/bin/env python3` which means it tries to use `python3` by default. `python3` no longer supports type `long`. This means that
```shell
$ ./binomial.py -n 150 -k 40
4408904561911885789946649584764715008
```
however, when it is run with `python2` it will show
```shell
$ python ./binomial.py -n 150 -k 40
4.40890456191e+36
``` 
---
* The `doctest` module has problems with returning integers vs floating point values if run with `python2`
```shell
$ python ./binomial.py --test
testing the module...
**********************************************************************
File "./binomial.py", line 85, in __main__.choose
Failed example:
    choose(5, 3)
Expected:
    10
Got:
    10.0
**********************************************************************
```
Even though the code says 
```python
logChoose = logfactorial(n, k) - logfactorial(n - k)
    if log:
        return logChoose
    else:
        return round(math.exp(logChoose)) # returns whole number
```
@cecileane and @coraallencoleman

**Comment by cecileane** [comment]
now that's a real "issue". awesome work!
